"""数据模式包 - 导出所有模式以便统一导入"""
from .user import (
    UserBase,
    UserCreate,
    UserLogin,
    UserResponse,
    UserWithToken,
    TokenPayload,
    PasswordReset,
)
from .novel import (
    NovelBase,
    NovelCreate,
    NovelUpdate,
    NovelPublish,
    NovelListItem,
    NovelDetail,
    NovelListResponse,
    AuthorInfo,
    ChapterSummary,
    CharacterSummary,
)
from .chapter import (
    ChapterBase,
    ChapterCreate,
    ChapterUpdate,
    ChapterReorder,
    ChapterListItem,
    ChapterDetail,
    ChapterListResponse,
    ChapterNavigation,
    # 互动小说功能相关
    ChoiceSelection,
    ChoiceResult,
    ChoiceHistory,
    ReadingProgressResponse,
    ReadingProgressUpdate,
    EndingInfo,
    EndingsList,
    MarkEndingRequest,
)
from .ai import (
    OutlineRequest,
    OutlineResponse,
    ContinueRequest,
    ContinueResponse,
    ExpandRequest,
    ExpandResponse,
    CharacterRequest,
    CharacterResponse,
    GeneratedCharacter,
    AIUsage,
    FormatOptimizeRequest,
    FormatOptimizeResponse,
    FormatOptimizeBatchRequest,
    FormatOptimizeBatchResponse,
    OptimizedChapterResult,
    RewriteRequest,
    RewriteResponse,
    # 冒险游戏相关
    OpeningGenerationRequest,
    OpeningGenerationResponse,
    ChoiceOption,
    StoryNodeGenerationRequest,
    StoryNodeGenerationResponse,
)
from .common import APIResponse, ErrorResponse
from .character import (
    CharacterBase,
    CharacterCreate,
    CharacterUpdate,
    CharacterItem,
    CharacterListResponse,
    WorldSettingBase,
    WorldSettingCreate,
    WorldSettingUpdate,
    WorldSettingItem,
    WorldSettingListResponse,
)

__all__ = [
    # 用户相关
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserWithToken",
    "TokenPayload",
    "PasswordReset",
    # 小说相关
    "NovelBase",
    "NovelCreate",
    "NovelUpdate",
    "NovelPublish",
    "NovelListItem",
    "NovelDetail",
    "NovelListResponse",
    "AuthorInfo",
    "ChapterSummary",
    "CharacterSummary",
    # 章节相关
    "ChapterBase",
    "ChapterCreate",
    "ChapterUpdate",
    "ChapterReorder",
    "ChapterListItem",
    "ChapterDetail",
    "ChapterListResponse",
    "ChapterNavigation",
    # 互动小说功能相关
    "ChoiceSelection",
    "ChoiceResult",
    "ChoiceHistory",
    "ReadingProgressResponse",
    "ReadingProgressUpdate",
    "EndingInfo",
    "EndingsList",
    "MarkEndingRequest",
    # AI相关
    "OutlineRequest",
    "OutlineResponse",
    "ContinueRequest",
    "ContinueResponse",
    "ExpandRequest",
    "ExpandResponse",
    "CharacterRequest",
    "CharacterResponse",
    "GeneratedCharacter",
    "AIUsage",
    "FormatOptimizeRequest",
    "FormatOptimizeResponse",
    "FormatOptimizeBatchRequest",
    "FormatOptimizeBatchResponse",
    "OptimizedChapterResult",
    "RewriteRequest",
    "RewriteResponse",
    # 冒险游戏相关
    "OpeningGenerationRequest",
    "OpeningGenerationResponse",
    "ChoiceOption",
    "StoryNodeGenerationRequest",
    "StoryNodeGenerationResponse",
    # 通用
    "APIResponse",
    "ErrorResponse",
    # 角色与世界观
    "CharacterBase",
    "CharacterCreate",
    "CharacterUpdate",
    "CharacterItem",
    "CharacterListResponse",
    "WorldSettingBase",
    "WorldSettingCreate",
    "WorldSettingUpdate",
    "WorldSettingItem",
    "WorldSettingListResponse",
]
